### ISSUE TITLE
Translated content not found

### ISSUE THREAD

**Issue by getit-kk** [OFFLINE-GmbH/oc-site-search-plugin#60]
On testpage I have this code
```
<h1>{{ 'homepage.content'|_ }}</h1>
that is my homepage
```
The content in h1-Tag ist translated by Rainlab.Translate into 'Das ist meine Homepage'.

If I search for 'my' I get 1 result but when I search for 'meine' I get nothing.

**Comment by tobias-kuendig** [comment]
Is this a CMS page? Please be aware that the plugin only supports searching through database contents. 

In this case the plugin cannot easily search your page since it would have to be rendered (for each language) before searching. Support for CMS pages is currently only experimental and won't work with dynamic content [as stated in the readme](https://github.com/OFFLINE-GmbH/oc-site-search-plugin#cms-pages-experimental).

**Comment by getit-kk** [comment]
You are right.
Its a CMS page.
