### ISSUE TITLE
Is there way to use CMS pages (experimental) with twig?

### ISSUE THREAD

**Issue by asystemg** [OFFLINE-GmbH/oc-site-search-plugin#61]
Is there way to parse twig and send it to plugin?

**Comment by tobias-kuendig** [comment]
It might be possible but not easy. Espacially since we would have to keep an index of the contents so we don't have to re-render all views for every search query.

Another way would be to search the already compiled cache files of October. This could lead to unexpected results though.

The easiest and cleanest way is to store your contents in the databases and use a `SearchProvider` class.

**Comment by Wachem** [comment]
Not resolving your question but maybe handy: My client requested a search function with the power to include his own 'search terms' and not the regular 'page content'. So, I've extended the CMS config fields and made a little adaptation to the CmsPagesResultsProvider class. This results in nice multilingual search results which trigger on your predefined terms.

![image](https://user-images.githubusercontent.com/6443046/51471358-c762d400-1d76-11e9-98bc-86d88e71eb7b.png)
![image](https://user-images.githubusercontent.com/6443046/51471455-05f88e80-1d77-11e9-9b07-1af592f38b2b.png)

**Comment by tobias-kuendig** [comment]
Closing this issue due to inactiviy. Simpmly reply in case your problem is not resolved.
