### ISSUE TITLE
Next and previous pagination links in ML do not contain lang code

### ISSUE THREAD

**Issue by Rike-cz** [OFFLINE-GmbH/oc-site-search-plugin#71]
Search result site URL is `www.domain.tld/de/suchen?q=something`.
Search detail URL works fine with Translate plugin, current lang code is added, e.g.: `www.domain.tld/de/article-1`. 
**But** pagination buttons do not have lang code in URL (`www.domain.tld/suchen?q=something&page=2` instead of `www.domain.tld/de/suchen?q=something&page=2`), so clicking goes to `www.domain.tld/suchen?q=something&page=2` and automatically redirects to `www.domain.tld/de/suchen` with no search results.

Is something wrong with my installation?

**Comment by tobias-kuendig** [comment]
> Is something wrong with my installation?

No, this is currently expected behaviour. The pagination links are unaware of the current locale. The problem here is that we cannot blindly prepend the locale to the pagination links. We need to check if the `forceUrl` property is set in the `localePicker` component. Otherwise there is no locale prefix in the url.

**Comment by tobias-kuendig** [comment]
Scratch that, I've found a better solution. This is fixed in v1.3.17.

Thank you for the bug report!

**Comment by Rike-cz** [comment]
What a quickness!
