### ISSUE TITLE
use git flow

### ISSUE THREAD

**Issue by mokeev1995** [OFFLINE-GmbH/oc-site-search-plugin#8]
it's might be useful for you to use git flow for making your product with versions/releases
for example:
```
master --*----------------------------/---
          \               /rc-0.1----/----
           \dev-\--------/----------------
                 \------/
        (example)d/bugfix/fix_typo_in_english_translation
        (example)d/feature/ukranian_language_added
        (example)d/hotfix/fix_security_issue
```

where ```d/hotfix/fix_security_issue```, ```d/feature/ukranian_language_added``` and ```d/bugfix/fix_typo_in_english_translation``` are branches from dev. when work is done, you should create pull request and merge all data to dev, after all changes you want to release, you should create and merge pull request from dev to rc-{relase number}, after all tests with this branch, you should create PR to master and create new revision.

**Comment by tobias-kuendig** [comment]
Hi

Thanks for you input. I'm aware of what git flow is and how to use it. Git flow is just one of many ways to use git and to organize a project. Since releases are managed via the October Marketplace and there aren't many contributions to the plugin yet, I like to keep it simple.

Maybe we'll switch to git flow in the future.
