### ISSUE TITLE
Sanitize user input to prevent XSS in search

### ISSUE THREAD

**Issue by cryptoluks** [OFFLINE-GmbH/oc-site-search-plugin#81]
Hi,

I stumbled across your project and found a XSS in the search field as shown below:

https://mall.offline.swiss/en/suche?q=%3Cscript%3Ealert%28%22this+should+not+happen%22%29%3C%2Fscript%3E

(Please notice that Chrome might block XSS browserside, so you might want to try it in Firefox.)

It seems that the user query is not properly sanitized. I submitted a pull request to fix this issue.

https://github.com/OFFLINE-GmbH/oc-site-search-plugin/pull/80

Matthias

**Comment by tobias-kuendig** [comment]
Thank you very much for bringing this up. This does not seem to be a problem with the SiteSearch plugin itself.

Preventing XSS is the job of the presentation layer (twig, in the case of October). 

Passing the input data through `filter_var` might break search results for certain queries, since `filter_var` actively removes characters from a string or replaces them with html entities. Just as an example:

```php
filter_var('It is > 3 but < 5 ', FILTER_SANITIZE_STRING);
> It is > 3 but

filter_var("It's true", FILTER_SANITIZE_STRING);
> It&#39;s true
```

Using the example from the README, twig takes care of the encoding:

```twig
{# no XSS! #}
<h2>Search results for {{ searchResults.query }}</h2>
```

It looks like the `| trans` filter used in the mall demo theme does not. 

```twig
<h2>{{ 'offline.mall::frontend.search.heading' | trans({query: searchResults.query}) }}</h2>
```

I'll have to look into this.

**Comment by tobias-kuendig** [comment]
This issue has been fixed in the mall demo theme by applying the `| escape` filter. Thanks again for bringing the issue up, @cryptoluks. 

The demo website will be updated shortly.
