### ISSUE TITLE
Closing search results

### ISSUE THREAD

**Issue by graphixela** [OFFLINE-GmbH/oc-site-search-plugin#85]
Is there any way to get the search results to close by clicking outside the form? I'm trying to do it with jQuery but I'm not having much luck.

**Comment by tobias-kuendig** [comment]
Something like that should work:

```js
$('body').on('click', function(e) {
    if ($(e.target).parent('#autocomplete-results').length == 0) {
        $('#autocomplete-results').hide();
    }
});
```

You'll have to make sure that the results are displayed again if the user starts typing again.

Another (nicer) solution is to place a fixed fullscreen element in your dom and render the autocomplete results in there. This way you can simply hide the results when a user clicks on this full screen div.

You should be able to find lots of examples online for things like this searching for `modals` or `focusout`. The plugin does not provide a complete solution but just a starting point since the autocomplete styling is very specific to our use-case.

**Comment by graphixela** [comment]
Thanks. Yes I was doing something similar to that but as you noted I have to then display the results again. I was just wondering if there was an easier way.

**Comment by graphixela** [comment]
I'll close this out. If anyone wanted to know what the end result was for now, I used:
$( ".search-form" ).focusin(function() {
  $('#autocomplete-results').show();
});
$( ".search-form" ).focusout(function() {
  $('#autocomplete-results').hide();
});
